# Generated by Django 6.0 on 2025-12-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(default=0, help_text='Match score 0-100'),
        ),
        migrations.AddField(
            model_name='application',
            name='match_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('not_matched', 'Not Matched')], default='not_matched', help_text='CV matching status', max_length=20),
        ),
    ]
