# Generated by Django 6.0 on 2025-12-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application_match_score_application_match_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('extracted_skills', models.JSONField(default=list)),
                ('match_score', models.IntegerField(default=0, help_text='Match score 0-100')),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('not_matched', 'Not Matched')], default='not_matched', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
            options={
                'unique_together': {('job', 'file_name')},
            },
        ),
    ]
